In [1]:
import numpy as np

In [2]:
a = np.zeros(5)

In [3]:
a.ndim

1

In [4]:
a

array([0., 0., 0., 0., 0.])

In [5]:
s = np.zeros(10, dtype = int)

In [6]:
s

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
s.ndim

1

In [9]:
d = np.zeros((3,3),dtype=int)

In [10]:
d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
d.ndim

2

In [12]:
f = np.ones(4)

In [13]:
f

array([1., 1., 1., 1.])

In [14]:
f.ndim

1

In [15]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [20]:
arr = np.zeros((2,3,3), dtype=int)

In [21]:
arr

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [22]:
arr.ndim

3

In [23]:
arr1 = np.zeros((2,2,3,3), dtype=int)

In [24]:
arr1

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

In [27]:
arr1.ndim

4

In [25]:
arr2 = np.zeros((2,2,2,3,3), dtype=int)

In [26]:
arr2

array([[[[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]],


        [[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]]],



       [[[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]],


        [[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]]]])

In [28]:
arr2.ndim

5

In [30]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
a = np.empty((3,4),dtype=int)

In [33]:
a

array([[      1748944624776,                  64,                   0,
                          0],
       [  27303467877924864, 3774968906149934131, 7147265824963049780,
        3630853898579895864],
       [3689119043440423985, 3486120574415351865, 4050817862299968048,
        7219327592870000998]])

In [36]:
s = np.empty((3,4))

In [37]:
s


array([[8.64093456e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.37961302e-306, 2.42336543e-057, 5.45483543e-090,
        4.27629973e-033],
       [5.54758024e+169, 3.37673986e-057, 3.99910963e+252,
        5.82471487e+257]])

In [38]:
import random

In [39]:
a=random.choice((1,2,3,4,5))
a

2

In [41]:
s=random.choice(("Ajay"))
s

'A'

In [42]:
f=random.choice(("Ajay"))
f

'j'

In [44]:
random.randrange(1,13)

5

In [45]:
random.random()

0.7323758223064702

In [46]:
lis = [1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [50]:
random.shuffle(lis)

In [51]:
lis

[3, 1, 5, 2, 4]

In [52]:
random.uniform(1,9)

6.536125755402465

In [53]:
np.random.random_sample()

0.941885117851506

In [60]:
np.random.random_sample((4,))#One Dimension arrray of 5 random values.

array([0.75322709, 0.55379087, 0.6303793 , 0.26761354])

In [61]:
np.random.rand(1)

array([0.4102911])

In [62]:
np.random.randn(3,4)

array([[-0.10957456,  0.42111042, -1.10867792,  0.9490761 ],
       [-2.53193114,  0.64924482, -0.47838985,  1.20856559],
       [ 1.02051277,  0.75968246,  0.51525971,  1.23405639]])

In [66]:
np.random.randint(1,5,size=(3,4))

array([[1, 3, 4, 4],
       [2, 2, 1, 1],
       [4, 1, 2, 1]], dtype=int32)

In [67]:
arr = np.random.randint(1,5,size=(3,4))

In [68]:
arr.ndim

2

In [69]:
arr.size

12

In [70]:
arr.shape

(3, 4)

In [71]:
arr.reshape(6,2)

array([[3, 1],
       [1, 4],
       [3, 3],
       [1, 2],
       [4, 3],
       [1, 4]], dtype=int32)

In [72]:
arr.reshape(4,5)

ValueError: cannot reshape array of size 12 into shape (4,5)

In [74]:
arr.reshape(3,-12)

array([[3, 1, 1, 4],
       [3, 3, 1, 2],
       [4, 3, 1, 4]], dtype=int32)

In [78]:
#In case of we do not know how many row or column should be then we can use known row or column row and negative value for unknown column or row.
#Numpy will automatically detect it

arr.reshape(6,-2)

array([[3, 1],
       [1, 4],
       [3, 3],
       [1, 2],
       [4, 3],
       [1, 4]], dtype=int32)

In [79]:
arr.reshape(3,4).base#It will show original array

array([[3, 1, 1, 4],
       [3, 3, 1, 2],
       [4, 3, 1, 4]], dtype=int32)

In [81]:
arr.reshape(2,2,3)

array([[[3, 1, 1],
        [4, 3, 3]],

       [[1, 2, 4],
        [3, 1, 4]]], dtype=int32)

In [82]:
arr.reshape(1,2,2,3)

array([[[[3, 1, 1],
         [4, 3, 3]],

        [[1, 2, 4],
         [3, 1, 4]]]], dtype=int32)

In [83]:
arr.reshape(1,1,2,2,3)

array([[[[[3, 1, 1],
          [4, 3, 3]],

         [[1, 2, 4],
          [3, 1, 4]]]]], dtype=int32)

In [96]:
arr = np.random.randint(1,10,(5,6))

In [97]:
arr

array([[7, 2, 7, 9, 5, 4],
       [5, 9, 9, 2, 4, 5],
       [7, 2, 4, 3, 8, 7],
       [7, 1, 1, 4, 6, 4],
       [7, 2, 6, 8, 1, 2]], dtype=int32)

In [98]:
arr>3

array([[ True, False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True,  True],
       [ True, False,  True, False,  True,  True],
       [ True, False, False,  True,  True,  True],
       [ True, False,  True,  True, False, False]])

In [99]:
arr[arr>3]

array([7, 7, 9, 5, 4, 5, 9, 9, 4, 5, 7, 4, 8, 7, 7, 4, 6, 4, 7, 6, 8],
      dtype=int32)

In [101]:
kartik = np.random.randint(1,10,(5,6))

In [102]:
kartik

array([[7, 5, 2, 2, 4, 4],
       [5, 6, 3, 1, 2, 1],
       [6, 7, 9, 9, 1, 2],
       [1, 3, 9, 5, 2, 1],
       [5, 1, 9, 1, 5, 6]], dtype=int32)

In [103]:
kartik[1:3,[0,2]]

array([[5, 3],
       [6, 9]], dtype=int32)

In [105]:
kartik[1:3]

array([[5, 6, 3, 1, 2, 1],
       [6, 7, 9, 9, 1, 2]], dtype=int32)

In [106]:
arr*kartik

array([[49, 10, 14, 18, 20, 16],
       [25, 54, 27,  2,  8,  5],
       [42, 14, 36, 27,  8, 14],
       [ 7,  3,  9, 20, 12,  4],
       [35,  2, 54,  8,  5, 12]], dtype=int32)