#Here I'm learning some basic things about Numpy.

In [1]:
import numpy as np

In [2]:
np.__version__

'2.5.1'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

Numpy stores the data in numpy array>> homogeneous data

In [4]:
l = [1,2,3,4,5,6,"Avi","Karti"]

In [7]:
arr = np.array(l)

In [8]:
type(arr)

numpy.ndarray

In [10]:
arr

array(['1', '2', '3', '4', '5', '6', 'Avi', 'Karti'], dtype='<U21')

In [11]:
arr.ndim

1

In [40]:
arr1 = ([[1,2,3,4,5,6],[1,2,3,"Karti","Indar","Avinash"]])

In [49]:
A = np.array(arr1)

In [42]:
arr2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [43]:
 AV = np.array(arr2)

In [44]:
AV.ndim

2

In [45]:
Karti = np.array(arr1)

In [46]:
matrix = np.matrix(arr2)

In [47]:
matrix.ndim

2

In [50]:
A.ndim 

2

In [76]:
KART = np.fromfunction(lambda i,j : i==j, (3,3))

In [77]:
KART

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [78]:
KART.ndim

2

In [79]:
KART.shape

(3, 3)

In [80]:
KART.size

9

In [81]:
Q = np.fromfunction(lambda i,j: i*j, (5,3))

In [82]:
Q 

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.],
       [0., 3., 6.],
       [0., 4., 8.]])

In [83]:
Q.ndim

2

In [84]:
Q.shape

(5, 3)

In [85]:
Q.size

15

In [86]:
#A new 1-D array initialized from text data in a string.
#Creating array from string
S = np.fromstring(' 22 33 44', sep = " ")

In [87]:
S

array([22., 33., 44.])

In [88]:
#Creating array from generator
iterator = (i for i in range(5))
np.fromiter(iterator, int)

array([0, 1, 2, 3, 4])

In [89]:
string = '12 34 56'
np.fromstring(string, sep = " ")

array([12., 34., 56.])

In [90]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.linspace() Return evenly spaced numbers over a specified interval.