In [1]:
import numpy as np

In [2]:
avinash = np.random.randint(1,10,(3,3))

In [3]:
avinash

array([[3, 7, 6],
       [4, 6, 5],
       [1, 5, 4]], dtype=int32)

In [4]:
avinash.flatten()

array([3, 7, 6, 4, 6, 5, 1, 5, 4], dtype=int32)

In [15]:
ad = np.expand_dims(avinash, axis=0)

In [7]:
karti = np.array([1,2,3,4])

In [8]:
karti

array([1, 2, 3, 4])

In [9]:
np.expand_dims(karti,axis=0)

array([[1, 2, 3, 4]])

In [10]:
np.expand_dims(karti,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
np.squeeze(avinash)

array([[3, 7, 6],
       [4, 6, 5],
       [1, 5, 4]], dtype=int32)

In [16]:
ad

array([[[3, 7, 6],
        [4, 6, 5],
        [1, 5, 4]]], dtype=int32)

In [17]:
np.squeeze(ad).ndim

2

In [18]:
ad.ndim

3

In [19]:
np.repeat(avinash,2)

array([3, 3, 7, 7, 6, 6, 4, 4, 6, 6, 5, 5, 1, 1, 5, 5, 4, 4], dtype=int32)